name: FriendList
author: Celeo
version: 1.8
main: net.thedarktide.celeo.friendlist.FriendList
commands:
  friendlist:
    description: Plugin-specific commands
    usage: /<command> <parameters>
  friend:
    description: Alias for /friendlist
    usage: /<command> <parameters>
  friends:
    description: Alias for /friendlist
    usage: /<command> <parameters>
  enemylist:
    description: Plugin-specific commands
    usage: /<command> <parameters>
  enemy:
    description: Alias for /enemylist
    usage: /<command> <parameters>
  enemies:
    description: Alias for /enemylist
    usage: /<command> <parameters>