name: FriendList
main: net.thedarktide.celeo.friendlist.FriendList
author: Celeo
version: 0.1
commands:
  friendlist:
    description: Plugin-specific commands
    usage: /<command> <parameters>
  friend:
    description: Alias for /friendlist
    usage: /<command> <parameters>